spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/gradebook_db
    username: postgres
    hikari:
      schema: public
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db.migration
    validateMigrationNaming: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
springfox:
  documentation:
    swagger-ui:
      enabled: true